# Generated by Django 3.0.8 on 2020-07-03 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HtmlTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targeturl', models.URLField(max_length=40, validators=[django.core.validators.RegexValidator('^978-4-[0-9]{4}-[0-9]{4}-[0-9X]{1}$', message='ISBNコードは正しい形式で指定してください。')], verbose_name='使いたい広告用素材URL')),
                ('articletitle', models.CharField(max_length=60, verbose_name='ブログのタイトル')),
                ('affiriateurl', models.URLField(max_length=60, validators=[django.core.validators.MinValueValidator(17, message='価格は正の整数で指定してください。')], verbose_name='アフィリエイト広告用url')),
                ('materialtype', models.CharField(choices=[('画像', '画像'), ('サムネイル用画像', 'サムネイル用画像'), ('ポップアップ用画像', 'ポップアップ用画像'), ('広告元へのリンク', '広告元へのリンク')], max_length=50, verbose_name='広告素材のタイプ')),
                ('blogtemplate', models.CharField(max_length=5000, verbose_name='template')),
                ('published', models.DateField(verbose_name='刊行日')),
            ],
        ),
    ]
