# Generated by Django 3.0.8 on 2020-07-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_htmltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmltag',
            name='blogtemplate',
            field=models.TextField(max_length=5000, verbose_name='template'),
        ),
    ]
